name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up Java JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build